<?php
  $lang['subtotal']		= 'Total parcial';
  $lang['orderid']		= 'Solicitar ID';
  $lang['number']		= 'Referencia';
  $lang['date']			= 'Fecha';
  $lang['time']			= 'Tiempo de facturación';  
  $lang['due']			= 'Facha de vencimiento';
  $lang['to']			= 'Facturación a';
  $lang['from']			= 'Nuestra información ';
  $lang['product']		= 'Producto';
  $lang['qty']			= 'Cantidad';
  $lang['price']		= 'Precio';
  $lang['discount']		= 'Descuento';
  $lang['vat']			= 'Impuestos';
  $lang['total']		= 'Total de';
  $lang['page']			= 'Página';
  $lang['page_of']		= 'de';
?>