<?php
  $lang['subtotal']		= 'Totale parziale';
  $lang['orderid']		= 'ID ordine';
  $lang['number']		= 'Riferimento';
  $lang['date']			= 'Data di fatturazione';
  $lang['time']			= 'Fatturazione';
  $lang['due']			= 'Scadenza';
  $lang['to']			= 'Fatturazione per';
  $lang['from']			= 'Nostre informazioni';
  $lang['product']		= 'Prodotto';
  $lang['qty']			= 'Quantità';
  $lang['price']		= 'Prezzo';
  $lang['discount']		= 'Sconto';
  $lang['vat']			= 'Imposta';
  $lang['total']		= 'Totale';
  $lang['page']			= 'Pagina';
  $lang['page_of']		= 'di';
?>