<?php
  $lang['subtotal']		= 'Subtotal';
  $lang['orderid']		= 'ID do pedido';
  $lang['number']		= 'Referência';
  $lang['date'] 		= 'Data de cobrança';
  $lang['time']			= 'Tempo de faturamento';
  $lang['due'] 			= 'Data de Vencimento';
  $lang['to'] 			= 'Faturamento para';
  $lang['from'] 		= 'Faturamento de';
  $lang['product'] 		= 'Produto';
  $lang['qty'] 			= 'Qtd';
  $lang['price'] 		= 'Preço';
  $lang['discount'] 	= 'Desconto';
  $lang['vat'] 			= 'IVA';
  $lang['total'] 		= 'Total';
  $lang['page'] 		= 'Página';
  $lang['page_of'] 		= 'do';
?>